### ISSUE TITLE
Q28 fails during naive bayes fit in 2020-11-17 nightly environment

### ISSUE THREAD

**Issue by beckernick** [rapidsai/gpu-bdb#140]
Q28 is failing in an environment from 2020-11-17 during the naive bayes fit call. This also happens in the 2020-11-16 environment, but not a 2020-11-12 environment, so it was introduced by a recent commit.

```
cd queries/q28; python tpcx_bb_query_28.py --config ../../benchmark_runner/benchmark_config.yaml ; cd ../../
Using default arguments
{
  "type": "Scheduler",
  "id": "Scheduler-113a1234-caae-4077-8e29-5a6012212623",
  "address": "tcp://10.33.228.70:8786",
  "services": {
    "dashboard": 8787
  },
  "workers": {}
}
Connected!
[I] [07:04:31.393816] [Delayed('_merge_counts_to_model-6e7b1e4f-200a-4e39-84d8-c341fa88265d')]
[I] [07:04:31.394280] [Delayed('_merge_counts_to_model-b7455c4e-016d-4be7-a82e-09d454378c91')]
[I] [07:04:31.394326] [<Future: finished, type: cuml.MultinomialNB, key: _fit-9dad00c5-881d-44f9-8f92-108a6631e7cf>]
[I] [07:04:31.394652] [Delayed('_merge_counts_to_model-b071bfe5-d3fb-4cfa-a905-4f2ada3e38c3')]
[I] [07:04:31.394980] [Delayed('_merge_counts_to_model-c8923527-437d-4911-b002-4180b98db499')]
[I] [07:04:31.395423] [Delayed('_merge_counts_to_model-c5a0704b-21e8-4072-be39-5207663ec82a')]
[I] [07:04:31.395768] [Delayed('_merge_counts_to_model-b7e59f5e-9377-4d10-9c19-e99387237d96')]
[I] [07:04:31.396105] [Delayed('_merge_counts_to_model-e532e45a-34a1-4ffd-8835-304c6010ade3')]
[I] [07:04:31.396415] [Delayed('_merge_counts_to_model-f64a787b-a3a7-43d0-9d3c-f628dec7f894')]
[I] [07:04:31.396452] [<Future: finished, type: cuml.MultinomialNB, key: _fit-3350630a-30dc-4952-8531-2795f0112d6e>]
[I] [07:04:31.396479] [<Future: finished, type: cuml.MultinomialNB, key: _fit-199e2b15-461e-48bd-8c91-b3308d41503e>]
[I] [07:04:31.396502] [<Future: finished, type: cuml.MultinomialNB, key: _fit-706f2bf8-3e69-4d16-9087-8d3d23179953>]
[I] [07:04:31.396524] [<Future: finished, type: cuml.MultinomialNB, key: _fit-aabc586b-1141-48bd-9ba1-f3bae9f6a2e7>]
[I] [07:04:31.396546] [<Future: finished, type: cuml.MultinomialNB, key: _fit-6a7a04b3-e54f-4eea-9827-7c50719f4cc6>]
[I] [07:04:31.396566] [<Future: finished, type: cuml.MultinomialNB, key: _fit-553b3861-131b-4584-9e09-9fc7ca1967a8>]
[I] [07:04:31.396587] [<Future: finished, type: cuml.MultinomialNB, key: _fit-cd6b16bb-0d75-453f-97e6-de7ed34f52a1>]
Encountered Exception while running query
Traceback (most recent call last):
  File "/raid/nicholasb/miniconda3/envs/rapids-tpcxbb-20201117/lib/python3.7/site-packages/xbb_tools/utils.py", line 280, in run_dask_cudf_query
    config=config,
  File "/raid/nicholasb/miniconda3/envs/rapids-tpcxbb-20201117/lib/python3.7/site-packages/xbb_tools/utils.py", line 61, in benchmark
    result = func(*args, **kwargs)
  File "tpcx_bb_query_28.py", line 341, in main
    client=client, train_data=train_data, test_data=test_data
  File "tpcx_bb_query_28.py", line 285, in post_etl_processing
    model.fit(X_train, y_train)
  File "/raid/nicholasb/miniconda3/envs/rapids-tpcxbb-20201117/lib/python3.7/site-packages/cuml/common/memory_utils.py", line 93, in cupy_rmm_wrapper
    return func(*args, **kwargs)
  File "/raid/nicholasb/miniconda3/envs/rapids-tpcxbb-20201117/lib/python3.7/site-packages/cuml/dask/naive_bayes/naive_bayes.py", line 190, in fit
    client=self.client)
  File "/raid/nicholasb/miniconda3/envs/rapids-tpcxbb-20201117/lib/python3.7/site-packages/cuml/dask/common/func.py", line 63, in reduce
    workers = [(first(who_has[m.key]), m) for m in futures]
  File "/raid/nicholasb/miniconda3/envs/rapids-tpcxbb-20201117/lib/python3.7/site-packages/cuml/dask/common/func.py", line 63, in <listcomp>
    workers = [(first(who_has[m.key]), m) for m in futures]
  File "/raid/nicholasb/miniconda3/envs/rapids-tpcxbb-20201117/lib/python3.7/site-packages/toolz/itertoolz.py", line 376, in first
    return next(iter(seq))
StopIteration
```

```
conda list | grep "rapids\|dask\|distr"
# packages in environment at /raid/nicholasb/miniconda3/envs/rapids-tpcxbb-20201117:
cudf                      0.17.0a201117   cuda_10.2_py37_g42fe2183f7_265    rapidsai-nightly
cuml                      0.17.0a201117   cuda10.2_py37_g59497faa0_119    rapidsai-nightly
dask                      2.30.0+57.g3e264491          pypi_0    pypi
dask-cuda                 0.17.0a201117           py37_42    rapidsai-nightly
dask-cudf                 0.17.0a201117   py37_g42fe2183f7_265    rapidsai-nightly
distributed               2.31.0.dev0+32.gd268735c          pypi_0    pypi
faiss-proc                1.0.0                      cuda    rapidsai-nightly
libcudf                   0.17.0a201117   cuda10.2_g42fe2183f7_265    rapidsai-nightly
libcuml                   0.17.0a201117   cuda10.2_g59497faa0_119    rapidsai-nightly
libcumlprims              0.17.0a201030   cuda10.2_g1fa28a5_8    rapidsai-nightly
librmm                    0.17.0a201106   cuda10.2_gb1ac445_43    rapidsai-nightly
rmm                       0.17.0a201106   cuda_10.2_py37_gb1ac445_43    rapidsai-nightly
ucx                       1.8.1+g6b29558       cuda10.2_0    rapidsai-nightly
ucx-proc                  1.0.0                       gpu    rapidsai-nightly
ucx-py                    0.17.0a201117   py37_g6b29558_17    rapidsai-nightly
```

**Comment by beckernick** [comment]
cc @dantegd @cjnolet

**Comment by beckernick** [comment]
Resolved by Vibhu and Dante
