### ISSUE TITLE
BSQL Q28 fails in 2020-10-09 nightly

### ISSUE THREAD

**Issue by beckernick** [rapidsai/gpu-bdb#151]
Looks like an input to the `build_features` function is somehow None, rather than a dask dataframe.

```python
28
This function has been Deprecated. It is recommended to use ddf.shuffle(on=[colnames])
This function has been Deprecated. It is recommended to use ddf.shuffle(on=[colnames])
Encountered Exception while running query
Traceback (most recent call last):
  File "/raid/nicholasb/new/tpcx-bb/tpcx_bb/xbb_tools/utils.py", line 324, in run_bsql_query
    config=config,
  File "/raid/nicholasb/new/tpcx-bb/tpcx_bb/xbb_tools/utils.py", line 61, in benchmark
    result = func(*args, **kwargs)
  File "queries/q28/tpcx_bb_query_28_sql.py", line 339, in main
    client=client, train_data=train_data, test_data=test_data
  File "queries/q28/tpcx_bb_query_28_sql.py", line 256, in post_etl_processing
    X_train = build_features(train_data)
  File "queries/q28/tpcx_bb_query_28_sql.py", line 67, in build_features
    X = t["pr_review_content"]
TypeError: 'NoneType' object is not subscriptable
```

**Comment by Christian8491** [comment]
With a today's env, (16 GPUs-dgx202) I tried 8 times this query (isolated) and what i got was:
Succeed: 2 times
Crashed: 6 times (all with the same message)

```
Traceback (most recent call last):
  File "/home/christianc/miniconda3/envs/bsql-tpcx/lib/python3.7/site-packages/xbb_tools/utils.py", line 326, in run_bsql_query
    config=config,
  File "/home/christianc/miniconda3/envs/bsql-tpcx/lib/python3.7/site-packages/xbb_tools/utils.py", line 63, in benchmark
    result = func(*args, **kwargs)
  File "tpcx_bb_query_28_sql.py", line 345, in main
    client=client, train_data=train_data, test_data=test_data
  File "tpcx_bb_query_28_sql.py", line 259, in post_etl_processing
    X_train = build_features(train_data)
  File "tpcx_bb_query_28_sql.py", line 79, in build_features
    X.compute_chunk_sizes()
  File "/home/christianc/miniconda3/envs/bsql-tpcx/lib/python3.7/site-packages/dask/array/core.py", line 1202, in compute_chunk_sizes
    [tuple([int(chunk) for chunk in chunks]) for chunks in compute(tuple(c))[0]]
  File "/home/christianc/miniconda3/envs/bsql-tpcx/lib/python3.7/site-packages/dask/base.py", line 454, in compute
    results = schedule(dsk, keys, **kwargs)
  File "/home/christianc/miniconda3/envs/bsql-tpcx/lib/python3.7/site-packages/distributed/client.py", line 2725, in get
    results = self.gather(packed, asynchronous=asynchronous, direct=direct)
  File "/home/christianc/miniconda3/envs/bsql-tpcx/lib/python3.7/site-packages/distributed/client.py", line 1992, in gather
    asynchronous=asynchronous,
  File "/home/christianc/miniconda3/envs/bsql-tpcx/lib/python3.7/site-packages/distributed/client.py", line 833, in sync
    self.loop, func, *args, callback_timeout=callback_timeout, **kwargs
  File "/home/christianc/miniconda3/envs/bsql-tpcx/lib/python3.7/site-packages/distributed/utils.py", line 340, in sync
    raise exc.with_traceback(tb)
  File "/home/christianc/miniconda3/envs/bsql-tpcx/lib/python3.7/site-packages/distributed/utils.py", line 324, in f
    result[0] = yield future
  File "/home/christianc/miniconda3/envs/bsql-tpcx/lib/python3.7/site-packages/tornado/gen.py", line 762, in run
    value = future.result()
  File "/home/christianc/miniconda3/envs/bsql-tpcx/lib/python3.7/site-packages/distributed/client.py", line 1851, in _gather
    raise exception.with_traceback(traceback)
  File "/home/christianc/miniconda3/envs/bsql-tpcx/lib/python3.7/site-packages/dask/optimization.py", line 963, in __call__
    return core.get(self.dsk, self.outkey, dict(zip(self.inkeys, args)))
  File "/home/christianc/miniconda3/envs/bsql-tpcx/lib/python3.7/site-packages/dask/core.py", line 151, in get
    result = _execute_task(task, cache)
  File "/home/christianc/miniconda3/envs/bsql-tpcx/lib/python3.7/site-packages/dask/core.py", line 121, in _execute_task
    return func(*(_execute_task(a, cache) for a in args))
  File "/home/christianc/miniconda3/envs/bsql-tpcx/lib/python3.7/site-packages/dask/utils.py", line 29, in apply
    return func(*args, **kwargs)
  File "/home/christianc/miniconda3/envs/bsql-tpcx/lib/python3.7/site-packages/dask/dataframe/core.py", line 5311, in apply_and_enforce
    df = func(*args, **kwargs)
  File "tpcx_bb_query_28_sql.py", line 51, in gpu_hashing_vectorizer
    return vec.fit_transform(x)
  File "/home/christianc/miniconda3/envs/bsql-tpcx/lib/python3.7/site-packages/cuml/feature_extraction/_vectorizers.py", line 885, in fit_transform
    return self.fit(X, y).transform(X)
  File "/home/christianc/miniconda3/envs/bsql-tpcx/lib/python3.7/site-packages/cuml/feature_extraction/_vectorizers.py", line 907, in transform
    tokenized_df = self._create_tokenized_df(docs)
  File "/home/christianc/miniconda3/envs/bsql-tpcx/lib/python3.7/site-packages/cuml/feature_extraction/_vectorizers.py", line 222, in _create_tokenized_df
    tokenized_df = cudf.concat(tokenized_df_ls)
  File "/home/christianc/miniconda3/envs/bsql-tpcx/lib/python3.7/site-packages/cudf/core/reshape.py", line 365, in concat
    sort=sort,
  File "/home/christianc/miniconda3/envs/bsql-tpcx/lib/python3.7/contextlib.py", line 74, in inner
    return func(*args, **kwds)
  File "/home/christianc/miniconda3/envs/bsql-tpcx/lib/python3.7/site-packages/cudf/core/frame.py", line 357, in _concat
    libcudf.concat.concat_tables(tables, ignore_index=ignore_index)
  File "cudf/_lib/concat.pyx", line 46, in cudf._lib.concat.concat_tables
  File "cudf/_lib/concat.pyx", line 54, in cudf._lib.concat.concat_tables
RuntimeError: cuDF failure at: /opt/conda/envs/rapids/conda-bld/libcudf_1607508461624/work/cpp/src/copying/concatenate.cu:369: Total number of concatenated rows exceeds size_type range
```
