### ISSUE TITLE
Q28 fails on sf1000 when spilling is enabled

### ISSUE THREAD

**Issue by ChrisJar** [rapidsai/gpu-bdb#174]
Q28 fails with error:

<details>
    <summary>Traceback</summary>
    
```
Traceback (most recent call last):
File "/raid/cjarrett/miniconda3/envs/rapids-tpcx-bb/lib/python3.7/site-packages/distributed/worker.py", line 1748, in transition_executing_done
self.put_key_in_memory(ts, value, transition=False)
File "/raid/cjarrett/miniconda3/envs/rapids-tpcx-bb/lib/python3.7/site-packages/distributed/worker.py", line 1982, in put_key_in_memory
self.data[ts.key] = value
File "/raid/cjarrett/miniconda3/envs/rapids-tpcx-bb/lib/python3.7/site-packages/dask_cuda/proxify_host_file.py", line 193, in __setitem__
value, proxied_id_to_proxy, found_proxies
File "/raid/cjarrett/miniconda3/envs/rapids-tpcx-bb/lib/python3.7/site-packages/dask_cuda/proxify_device_objects.py", line 37, in proxify_device_objects
return dispatch(obj, proxied_id_to_proxy, found_proxies)
File "/raid/cjarrett/miniconda3/envs/rapids-tpcx-bb/lib/python3.7/site-packages/dask/utils.py", line 509, in __call__
return meth(arg, *args, **kwargs)
File "/raid/cjarrett/miniconda3/envs/rapids-tpcx-bb/lib/python3.7/site-packages/dask_cuda/proxify_device_objects.py", line 53, in proxify_device_object_default
return proxify(obj, proxied_id_to_proxy, found_proxies)
File "/raid/cjarrett/miniconda3/envs/rapids-tpcx-bb/lib/python3.7/site-packages/dask_cuda/proxify_device_objects.py", line 45, in proxify
proxied_id_to_proxy[_id] = ret = asproxy(obj, subclass=subclass)
File "/raid/cjarrett/miniconda3/envs/rapids-tpcx-bb/lib/python3.7/site-packages/dask_cuda/proxy_object.py", line 56, in asproxy
val = val()
File "cupy/core/core.pyx", line 1260, in cupy.core.core.ndarray.__len__
TypeError: len() of unsized object
```

</details>

Environment details:

<details>
<summary>Environment</summary>

```
DEVICE_MEMORY_LIMIT="40GB"
POOL_SIZE="80GB"
CLUSTER_MODE="NVLINK"
DASK_JIT_UNSPILL=True

+-----------------------------------------------------------------------------+
| NVIDIA-SMI 450.80.02    Driver Version: 450.80.02    CUDA Version: 11.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Graphics Device     On   | 00000000:01:00.0 Off |                    0 |
| N/A   36C    P0    61W / 275W |      0MiB / 81252MiB |      0%      Default |
|                               |                      |             Disabled |
+-------------------------------+----------------------+----------------------+
|   1  Graphics Device     On   | 00000000:47:00.0 Off |                    0 |
| N/A   36C    P0    59W / 275W |      0MiB / 81252MiB |      0%      Default |
|                               |                      |             Disabled |
+-------------------------------+----------------------+----------------------+
|   2  Graphics Device     On   | 00000000:81:00.0 Off |                    0 |
| N/A   36C    P0    62W / 275W |      0MiB / 81252MiB |      0%      Default |
|                               |                      |             Disabled |
+-------------------------------+----------------------+----------------------+
|   3  DGX Display         On   | 00000000:C1:00.0  On |                  N/A |
| 34%   42C    P8    N/A /  50W |    135MiB /  3911MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   4  Graphics Device     On   | 00000000:C2:00.0 Off |                    0 |
| N/A   35C    P0    58W / 275W |      0MiB / 81252MiB |      0%      Default |
|                               |                      |             Disabled |
+-------------------------------+----------------------+----------------------+

# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       1_gnu    conda-forge
abseil-cpp                20200225.2           he1b5a44_2    conda-forge
aiohttp                   3.7.3            py37h5e8e339_1    conda-forge
alsa-lib                  1.2.3                h516909a_0    conda-forge
anyio                     2.0.2            py37h89c1867_4    conda-forge
argon2-cffi               20.1.0           py37h5e8e339_2    conda-forge
arrow-cpp                 1.0.1           py37h2318771_14_cuda    conda-forge
arrow-cpp-proc            3.0.0                      cuda    conda-forge
async-timeout             3.0.1                   py_1000    conda-forge
async_generator           1.10                       py_0    conda-forge
asyncssh                  2.5.0              pyhd8ed1ab_0    conda-forge
attrs                     20.3.0             pyhd3deb0d_0    conda-forge
aws-c-common              0.4.59               h36c2ea0_1    conda-forge
aws-c-event-stream        0.1.6                had2084c_6    conda-forge
aws-checksums             0.1.10               h4e93380_0    conda-forge
aws-sdk-cpp               1.8.63               h9b98462_0    conda-forge
babel                     2.9.0              pyhd3deb0d_0    conda-forge
backcall                  0.2.0              pyh9f0ad1d_0    conda-forge
backports                 1.0                        py_2    conda-forge
backports.functools_lru_cache 1.6.1                      py_0    conda-forge
blazingsql                0.18.0a0                 pypi_0    pypi
bleach                    3.2.3              pyh44b312d_0    conda-forge
blinker                   1.4                        py_1    conda-forge
bokeh                     2.2.3            py37h89c1867_0    conda-forge
boost-cpp                 1.72.0               h9d3c048_4    conda-forge
brotli                    1.0.9                h9c3ff4c_4    conda-forge
brotlipy                  0.7.0           py37h5e8e339_1001    conda-forge
bzip2                     1.0.8                h7f98852_4    conda-forge
c-ares                    1.17.1               h36c2ea0_0    conda-forge
ca-certificates           2020.12.5            ha878542_0    conda-forge
cachetools                4.2.1              pyhd8ed1ab_0    conda-forge
cairo                     1.16.0            h7979940_1007    conda-forge
catalogue                 1.0.0            py37h89c1867_3    conda-forge
certifi                   2020.12.5        py37h89c1867_1    conda-forge
cffi                      1.14.4           py37hc58025e_1    conda-forge
chardet                   3.0.4           py37he5f6b98_1008    conda-forge
click                     7.1.2              pyh9f0ad1d_0    conda-forge
cloudpickle               1.6.0                      py_0    conda-forge
cryptography              3.3.1            py37h7f0c10b_1    conda-forge
cudatoolkit               11.0.221             h6bb024c_0    nvidia
cudf                      0.18.0a210128   cuda_11.0_py37_g7d52970a37_213    rapidsai-nightly
cudnn                     8.0.0                cuda11.0_0    nvidia
cuml                      0.18.0a210128   cuda11.0_py37_ge0f6a80a3_88    rapidsai-nightly
cupy                      8.0.0            py37h0ce7dbb_0    rapidsai-nightly
cymem                     2.0.5            py37hcd2ae1e_1    conda-forge
cyrus-sasl                2.1.27               h3274739_1    conda-forge
cython-blis               0.7.4            py37h902c9e0_0    conda-forge
cytoolz                   0.11.0           py37h5e8e339_3    conda-forge
dask                      2021.1.1           pyhd8ed1ab_0    conda-forge
dask-core                 2021.1.1           pyhd8ed1ab_0    conda-forge
dask-cuda                 0.18.0a201211           py37_39    rapidsai-nightly
dask-cudf                 0.18.0a210128   py37_g7d52970a37_213    rapidsai-nightly
decorator                 4.4.2                      py_0    conda-forge
defusedxml                0.6.0                      py_0    conda-forge
distributed               2021.1.1         py37h89c1867_0    conda-forge
dlpack                    0.3                  he1b5a44_1    conda-forge
en-core-web-sm            2.3.1                    pypi_0    pypi
entrypoints               0.3             pyhd8ed1ab_1003    conda-forge
faiss-proc                1.0.0                      cuda    rapidsai-nightly
fastavro                  1.3.0            py37h5e8e339_0    conda-forge
fastrlock                 0.5              py37hcd2ae1e_2    conda-forge
fontconfig                2.13.1            hba837de_1004    conda-forge
freetype                  2.10.4               h0708190_1    conda-forge
fsspec                    0.8.5              pyhd8ed1ab_0    conda-forge
future                    0.18.2           py37h89c1867_3    conda-forge
gettext                   0.19.8.1          h0b5b191_1005    conda-forge
gflags                    2.2.2             he1b5a44_1004    conda-forge
giflib                    5.2.1                h36c2ea0_2    conda-forge
glog                      0.4.0                h49b9bf7_3    conda-forge
google-auth               1.24.0             pyhd3deb0d_0    conda-forge
google-auth-oauthlib      0.4.2              pyhd8ed1ab_0    conda-forge
google-cloud-cpp          1.16.0               he4a878c_2    conda-forge
google-cloud-cpp-common   0.25.0               he83eced_7    conda-forge
googleapis-cpp            0.10.0               h6b1abdc_4    conda-forge
graphite2                 1.3.13            h58526e2_1001    conda-forge
grpc-cpp                  1.32.0               h7997a97_1    conda-forge
gspread                   3.6.0              pyh9f0ad1d_0    conda-forge
harfbuzz                  2.7.4                h5cf4720_0    conda-forge
heapdict                  1.0.1                      py_0    conda-forge
httplib2                  0.18.1             pyh9f0ad1d_0    conda-forge
icu                       68.1                 h58526e2_0    conda-forge
idna                      2.10               pyh9f0ad1d_0    conda-forge
importlib-metadata        3.4.0            py37h89c1867_0    conda-forge
importlib_metadata        3.4.0                hd8ed1ab_0    conda-forge
ipykernel                 5.4.3            py37h888b3d9_0    conda-forge
ipython                   7.19.0           py37h888b3d9_2    conda-forge
ipython_genutils          0.2.0                      py_1    conda-forge
jedi                      0.17.2           py37h89c1867_1    conda-forge
jinja2                    2.11.2             pyh9f0ad1d_0    conda-forge
joblib                    1.0.0              pyhd8ed1ab_0    conda-forge
jpeg                      9d                   h36c2ea0_0    conda-forge
jpype1                    1.2.1            py37h2527ec5_0    conda-forge
json5                     0.9.5              pyh9f0ad1d_0    conda-forge
jsonschema                3.2.0                      py_2    conda-forge
jupyter-server-proxy      1.5.3                    pypi_0    pypi
jupyter_client            6.1.11             pyhd8ed1ab_1    conda-forge
jupyter_core              4.7.0            py37h89c1867_1    conda-forge
jupyter_server            1.2.2            py37h89c1867_1    conda-forge
jupyterlab                3.0.5              pyhd8ed1ab_0    conda-forge
jupyterlab_pygments       0.1.2              pyh9f0ad1d_0    conda-forge
jupyterlab_server         2.1.3              pyhd8ed1ab_0    conda-forge
krb5                      1.17.2               h926e7f8_0    conda-forge
lcms2                     2.11                 hcbb858e_1    conda-forge
ld_impl_linux-64          2.35.1               hea4e1c9_1    conda-forge
libblas                   3.8.0               17_openblas    conda-forge
libcblas                  3.8.0               17_openblas    conda-forge
libcrc32c                 1.1.1                h9c3ff4c_2    conda-forge
libcudf                   0.18.0a210128   cuda11.0_g7d52970a37_213    rapidsai-nightly
libcuml                   0.18.0a210128   cuda11.0_ge0f6a80a3_88    rapidsai-nightly
libcumlprims              0.18.0a201203   cuda11.0_gff080f3_0    rapidsai-nightly
libcurl                   7.71.1               hcdd3856_8    conda-forge
libedit                   3.1.20191231         he28a2e2_2    conda-forge
libev                     4.33                 h516909a_1    conda-forge
libevent                  2.1.10               hcdb4288_3    conda-forge
libfaiss                  1.6.3           h328c4c8_1_cuda    rapidsai-nightly
libffi                    3.3                  h58526e2_2    conda-forge
libgcc-ng                 9.3.0               h2828fa1_18    conda-forge
libgfortran-ng            9.3.0               hff62375_18    conda-forge
libgfortran5              9.3.0               hff62375_18    conda-forge
libglib                   2.66.4               h748fe8e_2    conda-forge
libgomp                   9.3.0               h2828fa1_18    conda-forge
libhwloc                  2.3.0                h5e5b7d1_1    conda-forge
libiconv                  1.16                 h516909a_0    conda-forge
liblapack                 3.8.0               17_openblas    conda-forge
libllvm10                 10.0.1               he513fc3_3    conda-forge
libnghttp2                1.41.0               h8cfc5f6_2    conda-forge
libntlm                   1.4               h7f98852_1002    conda-forge
libopenblas               0.3.10          pthreads_h4812303_5    conda-forge
libpng                    1.6.37               h21135ba_2    conda-forge
libprotobuf               3.13.0.1             h8b12597_0    conda-forge
librmm                    0.18.0a210128   cuda11.0_gafe237c_26    rapidsai-nightly
libsodium                 1.0.18               h36c2ea0_1    conda-forge
libssh2                   1.9.0                hab1572f_5    conda-forge
libstdcxx-ng              9.3.0               h6de172a_18    conda-forge
libthrift                 0.13.0               h5aa387f_6    conda-forge
libtiff                   4.2.0                hdc55705_0    conda-forge
libutf8proc               2.6.1                h7f98852_0    conda-forge
libuuid                   2.32.1            h7f98852_1000    conda-forge
libwebp-base              1.1.0                h36c2ea0_3    conda-forge
libxcb                    1.13              h7f98852_1003    conda-forge
libxml2                   2.9.10               h72842e0_3    conda-forge
llvmlite                  0.35.0           py37h9d7f4d0_1    conda-forge
locket                    0.2.0                      py_2    conda-forge
lz4-c                     1.9.2                he1b5a44_3    conda-forge
markupsafe                1.1.1            py37h5e8e339_3    conda-forge
mistune                   0.8.4           py37h5e8e339_1003    conda-forge
msgpack-python            1.0.2            py37h2527ec5_1    conda-forge
multidict                 5.1.0            py37h5e8e339_1    conda-forge
murmurhash                1.0.5            py37hcd2ae1e_0    conda-forge
nbclassic                 0.2.6              pyhd8ed1ab_0    conda-forge
nbclient                  0.5.1                      py_0    conda-forge
nbconvert                 6.0.7            py37h89c1867_3    conda-forge
nbformat                  5.1.2              pyhd8ed1ab_1    conda-forge
nccl                      2.7.8.1            h4962215_100    nvidia
ncurses                   6.2                  h58526e2_4    conda-forge
nest-asyncio              1.4.3              pyhd8ed1ab_0    conda-forge
netifaces                 0.10.9          py37h5e8e339_1003    conda-forge
notebook                  6.2.0            py37h89c1867_0    conda-forge
numba                     0.52.0           py37hdc94413_0    conda-forge
numpy                     1.19.5           py37haa41c4c_1    conda-forge
nvtx                      0.2.1            py37h5e8e339_2    conda-forge
oauth2client              4.1.3                      py_0    conda-forge
oauthlib                  3.0.1                      py_0    conda-forge
olefile                   0.46               pyh9f0ad1d_1    conda-forge
openjdk                   11.0.8               hacce0ff_0    conda-forge
openssl                   1.1.1i               h7f98852_0    conda-forge
orc                       1.6.5                hd3605a7_0    conda-forge
packaging                 20.8               pyhd3deb0d_0    conda-forge
pandas                    1.1.5            py37hdc94413_0    conda-forge
pandoc                    2.11.4               h7f98852_0    conda-forge
pandocfilters             1.4.2                      py_1    conda-forge
parquet-cpp               1.5.1                         2    conda-forge
parso                     0.7.1              pyh9f0ad1d_0    conda-forge
partd                     1.1.0                      py_0    conda-forge
pcre                      8.44                 he1b5a44_0    conda-forge
pexpect                   4.8.0              pyh9f0ad1d_2    conda-forge
pickleshare               0.7.5                   py_1003    conda-forge
pillow                    8.1.0            py37he6b4880_1    conda-forge
pip                       21.0               pyhd8ed1ab_1    conda-forge
pixman                    0.40.0               h36c2ea0_0    conda-forge
plac                      0.9.6                      py_1    conda-forge
preshed                   3.0.5            py37hcd2ae1e_0    conda-forge
prometheus_client         0.9.0              pyhd3deb0d_0    conda-forge
prompt-toolkit            3.0.14             pyha770c72_0    conda-forge
protobuf                  3.13.0.1         py37h745909e_1    conda-forge
psutil                    5.8.0            py37h5e8e339_1    conda-forge
pthread-stubs             0.4               h36c2ea0_1001    conda-forge
ptyprocess                0.7.0              pyhd3deb0d_0    conda-forge
pyarrow                   1.0.1           py37hbeecfa9_14_cuda    conda-forge
pyasn1                    0.4.8                      py_0    conda-forge
pyasn1-modules            0.2.7                      py_0    conda-forge
pycparser                 2.20               pyh9f0ad1d_2    conda-forge
pygments                  2.7.4              pyhd8ed1ab_0    conda-forge
pyhive                    0.6.3              pyhd3deb0d_0    conda-forge
pyjwt                     2.0.1              pyhd8ed1ab_0    conda-forge
pynvml                    8.0.4                      py_1    conda-forge
pyopenssl                 20.0.1             pyhd8ed1ab_0    conda-forge
pyparsing                 2.4.7              pyh9f0ad1d_0    conda-forge
pyrsistent                0.17.3           py37h5e8e339_2    conda-forge
pysocks                   1.7.1            py37h89c1867_3    conda-forge
python                    3.7.9           hffdb5ce_0_cpython    conda-forge
python-dateutil           2.8.1                      py_0    conda-forge
python_abi                3.7                     1_cp37m    conda-forge
pytz                      2020.5             pyhd8ed1ab_0    conda-forge
pyyaml                    5.4.1            py37h5e8e339_0    conda-forge
pyzmq                     20.0.0           py37h499b945_1    conda-forge
re2                       2020.10.01           he1b5a44_0    conda-forge
readline                  8.0                  he28a2e2_2    conda-forge
requests                  2.25.1             pyhd3deb0d_0    conda-forge
requests-oauthlib         1.3.0              pyh9f0ad1d_0    conda-forge
rmm                       0.18.0a210128   cuda_11.0_py37_gafe237c_26    rapidsai-nightly
rsa                       4.7                pyhd3deb0d_0    conda-forge
sasl                      0.2.1           py37h3340039_1002    conda-forge
scikit-learn              0.24.1           py37h69acf81_0    conda-forge
scipy                     1.6.0            py37h14a347d_0    conda-forge
send2trash                1.5.0                      py_0    conda-forge
setuptools                49.6.0           py37h89c1867_3    conda-forge
simpervisor               0.4                      pypi_0    pypi
six                       1.15.0             pyh9f0ad1d_0    conda-forge
snappy                    1.1.8                he1b5a44_3    conda-forge
sniffio                   1.2.0            py37h89c1867_1    conda-forge
sortedcontainers          2.3.0              pyhd8ed1ab_0    conda-forge
spacy                     2.3.5            py37h6dcda5c_0    conda-forge
spdlog                    1.7.0                hc9558a2_2    conda-forge
sqlalchemy                1.3.22           py37h5e8e339_1    conda-forge
sqlite                    3.34.0               h74cdb3f_0    conda-forge
srsly                     1.0.5            py37hcd2ae1e_0    conda-forge
tblib                     1.6.0                      py_0    conda-forge
terminado                 0.9.2            py37h89c1867_0    conda-forge
testpath                  0.4.4                      py_0    conda-forge
thinc                     7.4.5            py37h6dcda5c_0    conda-forge
threadpoolctl             2.1.0              pyh5ca1d4c_0    conda-forge
thrift                    0.13.0           py37h3340039_2    conda-forge
thrift_sasl               0.4.2            py37h8f50634_0    conda-forge
tk                        8.6.10               h21135ba_1    conda-forge
toolz                     0.11.1                     py_0    conda-forge
tornado                   6.1              py37h5e8e339_1    conda-forge
tqdm                      4.56.0             pyhd8ed1ab_0    conda-forge
traitlets                 5.0.5                      py_0    conda-forge
treelite                  1.0.0rc1         py37hfdac9b6_1    conda-forge
treelite-runtime          1.0.0rc1                 pypi_0    pypi
typing-extensions         3.7.4.3                       0    conda-forge
typing_extensions         3.7.4.3                    py_0    conda-forge
ucx                       1.9.0+gcd9efd3       cuda11.0_0    rapidsai-nightly
ucx-proc                  1.0.0                       gpu    rapidsai-nightly
ucx-py                    0.18.0a210128   py37_gcd9efd3_10    rapidsai-nightly
urllib3                   1.26.3             pyhd8ed1ab_0    conda-forge
wasabi                    0.8.1              pyh44b312d_0    conda-forge
wcwidth                   0.2.5              pyh9f0ad1d_2    conda-forge
webencodings              0.5.1                      py_1    conda-forge
wheel                     0.36.2             pyhd3deb0d_0    conda-forge
xbb-tools                 0.2                      pypi_0    pypi
xorg-fixesproto           5.0               h14c3975_1002    conda-forge
xorg-inputproto           2.3.2             h7f98852_1002    conda-forge
xorg-kbproto              1.0.7             h7f98852_1002    conda-forge
xorg-libice               1.0.10               h516909a_0    conda-forge
xorg-libsm                1.2.3             h84519dc_1000    conda-forge
xorg-libx11               1.6.12               h516909a_0    conda-forge
xorg-libxau               1.0.9                h7f98852_0    conda-forge
xorg-libxdmcp             1.1.3                h7f98852_0    conda-forge
xorg-libxext              1.3.4                h516909a_0    conda-forge
xorg-libxfixes            5.0.3             h516909a_1004    conda-forge
xorg-libxi                1.7.10               h516909a_0    conda-forge
xorg-libxrender           0.9.10            h516909a_1002    conda-forge
xorg-libxtst              1.2.3             h516909a_1002    conda-forge
xorg-recordproto          1.14.2            h516909a_1002    conda-forge
xorg-renderproto          0.11.1            h14c3975_1002    conda-forge
xorg-xextproto            7.3.0             h7f98852_1002    conda-forge
xorg-xproto               7.0.31            h7f98852_1007    conda-forge
xz                        5.2.5                h516909a_1    conda-forge
yaml                      0.2.5                h516909a_0    conda-forge
yarl                      1.6.3            py37h5e8e339_1    conda-forge
zeromq                    4.3.3                h58526e2_3    conda-forge
zict                      2.0.0                      py_0    conda-forge
zipp                      3.4.0                      py_0    conda-forge
zlib                      1.2.11            h516909a_1010    conda-forge
zstd                      1.4.8                hdf46e1d_0    conda-forge

```

</details>

**Note:** This query does not fail with SF1, only SF1K

**Comment by madsbk** [comment]
@ChrisJar can you confirm that https://github.com/rapidsai/dask-cuda/pull/503 fixes the issue?

**Comment by ChrisJar** [comment]
> @ChrisJar can you confirm that [rapidsai/dask-cuda#503](https://github.com/rapidsai/dask-cuda/pull/503) fixes the issue?

Issue is fixed! Thanks!
