### ISSUE TITLE
Q05 fails converting empty pandas dataframe to cudf dataframe

### ISSUE THREAD

**Issue by beckernick** [rapidsai/gpu-bdb#177]
In the 2021-02-02 nightly, q05 fails converting an empty, int64 typed pandas dataframe to a cudf dataframe. Cross-posting as a cudf issue with the minimal reproducer.

```
Encountered Exception while running query
Traceback (most recent call last):
  File "/raid/nicholasb/gpu-bdb/tpcx_bb/xbb_tools/utils.py", line 280, in run_dask_cudf_query
    config=config,
  File "/raid/nicholasb/gpu-bdb/tpcx_bb/xbb_tools/utils.py", line 61, in benchmark
    result = func(*args, **kwargs)
  File "queries/q05/tpcx_bb_query_05.py", line 209, in main
    df = cudf.from_pandas(pd.DataFrame.from_dict(meta_d, dtype="int64"))
  File "/home/nicholasb/conda/envs/rapids-tpcxbb-20210202/lib/python3.7/site-packages/cudf/core/dataframe.py", line 7467, in from_pandas
    return DataFrame.from_pandas(obj, nan_as_null=nan_as_null)
  File "/home/nicholasb/conda/envs/rapids-tpcxbb-20210202/lib/python3.7/site-packages/cudf/core/dataframe.py", line 5228, in from_pandas
    col_value.array, nan_as_null=nan_as_null
  File "/home/nicholasb/conda/envs/rapids-tpcxbb-20210202/lib/python3.7/site-packages/cudf/core/column/column.py", line 1873, in as_column
    from_pandas=True if nan_as_null is None else nan_as_null,
  File "pyarrow/array.pxi", line 265, in pyarrow.lib.array
  File "pyarrow/array.pxi", line 76, in pyarrow.lib._ndarray_to_array
  File "pyarrow/array.pxi", line 64, in pyarrow.lib._ndarray_to_type
  File "pyarrow/error.pxi", line 107, in pyarrow.lib.check_status
pyarrow.lib.ArrowTypeError: Did not pass numpy.dtype object
```

**Comment by beckernick** [comment]
Root cause is unrelated to empty dataframes.

https://github.com/rapidsai/cudf/issues/7280

**Comment by beckernick** [comment]
This will be resolved when https://github.com/BlazingDB/blazingsql/issues/1304 is resolved.

**Comment by beckernick** [comment]
This should be resolved by https://github.com/conda-forge/conda-forge-repodata-patches-feedstock/pull/120

**Comment by beckernick** [comment]
Closing as conda-forge/conda-forge-repodata-patches-feedstock#120 has merged.
