### ISSUE TITLE
Several queries failing

### ISSUE THREAD

**Issue by randerzander** [rapidsai/gpu-bdb#219]
Several queries are failing with the latest nightlies:
q03, q12, q17 are the ones I noticed:

Trace is the same:
```
17                                                                                 
Encountered Exception while running query                
Traceback (most recent call last):                                                 
  File "/home/rgelhausen/gpu-bdb/gpu_bdb/bdb_tools/utils.py", line 276, in run_dask
_cudf_query                         
    results = benchmark(                                                           
  File "/home/rgelhausen/gpu-bdb/gpu_bdb/bdb_tools/utils.py", line 61, in benchmark
    result = func(*args, **kwargs)
  File "queries/q17/gpu_bdb_query_17.py", line 185, in main                        
    grouped_df = grouped_df.compute()                                              
  File "/home/rgelhausen/conda/envs/rapids-gpu-bdb/lib/python3.8/site-packages/dask
/base.py", line 285, in compute
    (result,) = compute(self, traverse=False, **kwargs)                            
  File "/home/rgelhausen/conda/envs/rapids-gpu-bdb/lib/python3.8/site-packages/dask
/base.py", line 567, in compute              
    results = schedule(dsk, keys, **kwargs)                                        
  File "/home/rgelhausen/conda/envs/rapids-gpu-bdb/lib/python3.8/site-packages/dist
ributed/client.py", line 2707, in get                                   
    results = self.gather(packed, asynchronous=asynchronous, direct=direct)        
  File "/home/rgelhausen/conda/envs/rapids-gpu-bdb/lib/python3.8/site-packages/dist
ributed/client.py", line 2021, in gather
    return self.sync(                                                              
  File "/home/rgelhausen/conda/envs/rapids-gpu-bdb/lib/python3.8/site-packages/dist
ributed/client.py", line 862, in sync                    
    return sync(                                                                   
  File "/home/rgelhausen/conda/envs/rapids-gpu-bdb/lib/python3.8/site-packages/dist
ributed/utils.py", line 338, in sync      
    raise exc.with_traceback(tb)                                                   
  File "/home/rgelhausen/conda/envs/rapids-gpu-bdb/lib/python3.8/site-packages/dist
ributed/utils.py", line 321, in f                       
    result[0] = yield future                                                       
  File "/home/rgelhausen/conda/envs/rapids-gpu-bdb/lib/python3.8/site-packages/torn
ado/gen.py", line 762, in run                                                      
    value = future.result()
 File "/home/rgelhausen/conda/envs/rapids-gpu-bdb/lib/python3.8/site-packages/dist
ributed/client.py", line 1886, in _gather
    raise exception.with_traceback(traceback)
  File "/home/rgelhausen/conda/envs/rapids-gpu-bdb/lib/python3.8/site-packages/dask
/optimization.py", line 969, in __call__
    return core.get(self.dsk, self.outkey, dict(zip(self.inkeys, args)))
  File "/home/rgelhausen/conda/envs/rapids-gpu-bdb/lib/python3.8/site-packages/dask
/core.py", line 151, in get
    result = _execute_task(task, cache)
  File "/home/rgelhausen/conda/envs/rapids-gpu-bdb/lib/python3.8/site-packages/dask
/core.py", line 121, in _execute_task
    return func(*(_execute_task(a, cache) for a in args))
  File "/home/rgelhausen/conda/envs/rapids-gpu-bdb/lib/python3.8/site-packages/dask
/utils.py", line 35, in apply
    return func(*args, **kwargs)
  File "/home/rgelhausen/conda/envs/rapids-gpu-bdb/lib/python3.8/site-packages/dask
/dataframe/core.py", line 5775, in apply_and_enforce
    df = func(*args, **kwargs)
  File "/home/rgelhausen/gpu-bdb/gpu_bdb/bdb_tools/utils.py", line 919, in <lambda>
    left_merge = lambda df_1, df_2: df_1.merge(
  File "/home/rgelhausen/conda/envs/rapids-gpu-bdb/lib/python3.8/contextlib.py", li
ne 75, in inner
    return func(*args, **kwds)
  File "/home/rgelhausen/conda/envs/rapids-gpu-bdb/lib/python3.8/site-packages/cudf
/core/dataframe.py", line 4486, in merge
    gdf_result = super()._merge(
  File "/home/rgelhausen/conda/envs/rapids-gpu-bdb/lib/python3.8/site-packages/cudf
/core/frame.py", line 3206, in _merge
    return merge(
  File "/home/rgelhausen/conda/envs/rapids-gpu-bdb/lib/python3.8/site-packages/cudf
/core/join/join.py", line 40, in merge
    mergeobj = merge_cls(
  File "/home/rgelhausen/conda/envs/rapids-gpu-bdb/lib/python3.8/site-packages/cudf
/core/join/join.py", line 485, in __init__
    super().__init__(*args, **kwargs)
  File "/home/rgelhausen/conda/envs/rapids-gpu-bdb/lib/python3.8/site-packages/cudf
/core/join/join.py", line 128, in __init__
    self._validate_merge_params(
  File "/home/rgelhausen/conda/envs/rapids-gpu-bdb/lib/python3.8/site-packages/cudf
/core/join/join.py", line 416, in _validate_merge_params
    same_named_columns = set(lhs._data) & set(rhs._data)
AttributeError: 'tuple' object has no attribute '_data'
```

Versions:
```
conda list | grep dask
dask                      2021.6.2           pyhd8ed1ab_0    conda-forge
dask-core                 2021.6.2           pyhd8ed1ab_0    conda-forge
dask-cuda                 21.08.00a210701         py38_32    rapidsai-nightly
dask-cudf                 21.08.00a210701 py38_g51b1c23b1b_236    rapidsai-nightly
(rapids-gpu-bdb) rgelhausen@rl-dgx2-r11-u7-rapids-dgx202:~/gpu-bdb/gpu_bdb/queries/load_test$ conda list | grep rapids
# packages in environment at /home/rgelhausen/conda/envs/rapids-gpu-bdb:
cudf                      21.08.00a210701 cuda_11.2_py38_g51b1c23b1b_236    rapidsai-nightly
```

**Comment by madsbk** [comment]
This should be fixed in https://github.com/dask/dask/pull/7838 and https://github.com/dask/dask/pull/7849. 
Because of https://github.com/rapidsai/cudf/pull/8581, we now use the new HighLevelGraph code patch in Dask/Distributed, which exposed some unknown bugs. I hope I have fixed all of them.

**Comment by randerzander** [comment]
This has been resolved now that the PRs linked above merged and a new Dask release was cut.
